### ISSUE TITLE
Update some runtimes

### ISSUE THREAD

**Issue by ali77gh** [ali77gh/language_performance_prime_algorithm#22]

**Comment by ali77gh** [comment]
Use dotnet instead mono
Update node
Update python

**Comment by mohamadnabikhani** [comment]
for nodejs, I used version 14 instead 12. it seems on Macbook m1 pro, it reduced the execution time from 2400 ms to 1700 ms. did you checked that?

**Comment by salarmotevalli** [comment]
I ran php code with version 8.1.2 and it took around 7 seconds.
So pleas update php compiler to.
