### ISSUE TITLE
Measure timings with unix time utility not language utilities

### ISSUE THREAD

**Issue by farooqkz** [ali77gh/language_performance_prime_algorithm#3]
Hello. It is obvious the at when you measure time within the language itself, the "fire up" time will be eliminated from the result leaving an incorrect result.

**Comment by ali77gh** [comment]
"incorrect" is strong word for that 😄.

I think eliminating "Fire Up" time make test closer to real senario. Lets say you have a nodejs application for your back-end service, then the "Fire Up" time is not that important for you, right? 
You measure performance by "response time" or RPS or...

But I think it will be fun if Someone add "Fire Up" (Unixtime - Looptime) to run.sh and Table of results.
So I will keep this issue open.

Thanks for your issue.😄
